#! /bin/bash

TIMETOCOMMIT=03
UFLAG=''
IFLAG=''
PFLAG=''
PACKAGES=""
NUMPACKAGES=""
UPDATES="43"

BBG='\033[40m' # black background
RBG='\033[41m' # red background
G='\033[0;32m' # green
CB='\033[1;36m' # cyan bold
GB='\033[1;32m' # green bold
WB='\033[1;37m' # white bold
NC='\033[0m' # no color

install() {
	pacman -S --noconfirm --disable-download-timeout --noprogressbar $PACKAGES
}

update() {
	pacman -Syu --noconfirm --disable-download-timeout --noprogressbar
}

checkTime() {
	[ $TIMETOCOMMIT -lt 0 ] && echo "supid: hour provided less than 0" && displayUsage
	[ $TIMETOCOMMIT -gt 23 ] && echo "supid: hour provided greater than 23" && displayUsage
	[ ${#TIMETOCOMMIT} -lt 2 ] && TIMETOCOMMIT="0$TIMETOCOMMIT"
}

commitTransaction() {
	clear
	[ UFLAG ] && update
	[ IFLAG ] && install
	[ PFLAG ] && printf "\n\nPowering off..." && sleep 5s && poweroff
}

displayUsage() {
	printf "
usage: autoinst [-h                           show this help message]
                [-i \"packages\"            install specified packages]
                [-u                     perform a full system update]
                [-p                        poweroff after completion]
                [-s hour       specify the starting hour, default 03]\n"
 exit 0
}

while getopts 'hi:ups:' flag; do
	case "${flag}" in
		h) displayUsage ;;
		i) IFLAG='true' && PACKAGES="${OPTARG}" && NUMPACKAGES=$(echo $PACKAGES | wc -w);;
		u) UFLAG='true' ;;
		p) PFLAG='true' ;;
		s) TIMETOCOMMIT="${OPTARG}" ;;
		*) displayUsage ;;
	esac
done

[ $OPTIND -eq 1 ] && displayUsage && exit 1

[ `whoami` != root ] && echo "Please run this script as root or using sudo" && exit 1

[ $UFLAG ] && echo "Refreshing pacman database..." && pacman -Sy >> /dev/null && UPDATES="$(pacman -Qu | wc -l)"

checkTime

while true; do
	HOUR=$(date "+%H")
	clear

printf "${G}╔═[${CB}Scheduled Update and Package Installer of Doom${G}]═╗\n"

printf "║${GB}${BBG} Transaction will contain:                        ${G}║"

[ $UFLAG ] && printf "\n║${CB} System update%$(( 30 - ${#UPDATES} ))s${NC}$UPDATES pkgs ${G}║" " "

[ $IFLAG ] && printf "\n║${CB} Package installation%$(( 23 - ${#NUMPACKAGES} ))s${NC}$NUMPACKAGES pkgs ${G}║" " "

if [ $PFLAG ]; then
	printf "\n${G}╚═[${CB}Time  ${NC}$(date "+%H:%M:%S")${G}]═[${CB}Continuing  ${NC}$TIMETOCOMMIT:00${G}]══${WB}${RBG} POWEROFF ${G}═╝\n"
else
	printf "\n${G}╚═[${CB}Time  ${NC}$(date "+%H:%M:%S")${G}]═[${CB}Continuing  ${NC}$TIMETOCOMMIT:00${G}]═════════════╝\n"
fi

[ $HOUR -eq $TIMETOCOMMIT ] && commitTransaction
	sleep 1s
done
